# Generated by Django 3.2.3 on 2024-10-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
